# 同步gitee工作流
name: Sync

# push到master分支触发
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'codeashen/Notes'
    steps:
      # 同步到gitee
      - name: Sync To Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 源仓库和目标仓库
          source-repo: git@github.com:codeashen/Notes.git
          destination-repo: git@gitee.com:codeashen/notes.git

#       # 重新构建gitee page
#       - name: Build Gitee Pages
#         uses: yanglbme/gitee-pages-action@main
#         with:
#           # gitee仓库信息
#           gitee-username: codeashen
#           gitee-password: ${{ secrets.GITEE_PASSWORD }}
#           gitee-repo: codeashen/Notes
#           branch: master
